import type { Metadata } from "next"
import { dm_sans } from "./fonts/fonts"
import "@/app/styles/global.scss"
import Navbar from "@/app/components/navbar/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
